import {useEffect,useRef,useState} from 'react';
import {LoaderCircle} from 'lucide-react';
import type {CopySection,Product,Settings,Artifact} from '../lib/types';
import {buildStoryboard,plannedPhotoCalls} from '../lib/storyboard';
import {renderPlanPreview} from '../lib/render';
export function photoLabel(origin:Artifact['photoOrigin']){return origin==='generated'?'AI 場景＋組版':origin==='prepared-scene'?'既有範例場景':origin==='original-crop'?'原圖局部特寫':origin==='context-preview'?'原圖情境示意':'原圖組版';}
export default function StoryboardPreview({product,settings,sections}:{product:Product;settings:Settings;sections:CopySection[]}){
 const [frames,setFrames]=useState<{id:string;title:string;purpose:string;url:string;origin:Artifact['photoOrigin']}[]>([]);const [loading,setLoading]=useState(false);const [error,setError]=useState('');
 const displayed=useRef<string[]>([]);useEffect(()=>()=>{displayed.current.forEach(u=>URL.revokeObjectURL(u));},[]);
 useEffect(()=>{let disposed=false;const urls:string[]=[];const timer=setTimeout(async()=>{setLoading(true);setError('');try{const plans=buildStoryboard(product,settings,sections).filter(p=>p.kind!=='video');const next=[];for(const plan of plans){if(disposed)break;const result=await renderPlanPreview(product,settings,plan);if(disposed)break;const url=URL.createObjectURL(result.blob);urls.push(url);next.push({id:plan.id,title:plan.kind==='banner'?'Banner':plan.purpose,purpose:plan.visualGoal,url,origin:result.photoOrigin});}if(!disposed){displayed.current.forEach(u=>URL.revokeObjectURL(u));displayed.current=urls;setFrames(next);}else urls.forEach(u=>URL.revokeObjectURL(u));}catch(e){urls.forEach(u=>URL.revokeObjectURL(u));if(!disposed)setError(e instanceof Error?e.message:'預覽未完成，請重試。');}finally{if(!disposed)setLoading(false);}},180);return()=>{disposed=true;clearTimeout(timer);};},[product,settings,sections]);
 const plans=buildStoryboard(product,settings,sections);const requests=plannedPhotoCalls(plans,{...settings,mode:'live'});
 return <section className="storyboard-preview" aria-label="免費套圖預覽"><div className="storyboard-heading"><div><span className="eyebrow">先看整套，再決定</span><h3>每張圖，都有自己的工作。</h3></div><span className="free-pill">免費預覽 · 0 次模型呼叫</span></div><p>先檢查構圖與閱讀順序。原圖、原圖特寫與既有範例場景會分開標示。</p>{loading&&<div className="storyboard-loading" role="status"><LoaderCircle size={15} className="spin"/>正在本機整理版型…</div>}{error&&<p role="alert">{error}</p>}<div className="storyboard-frames">{frames.map((frame,i)=><figure key={frame.id}><img src={frame.url} alt={`${i+1}. ${frame.title} 免費版型預覽`}/><figcaption><strong><span>{String(i+1).padStart(2,'0')}</span>{frame.title}</strong><small>{photoLabel(frame.origin)}</small></figcaption></figure>)}</div><p className="storyboard-note">若之後啟用 AI：本套預計需要 {requests} 次新照片請求{settings.outputs.includes('video')?'，另有 1 次影片請求':''}。原圖細節與規格不重複生圖。</p></section>;
}
