import { useEffect,useRef,useState } from 'react';
import { ArrowDownToLine,ArrowLeft,ArrowRight,Check,CheckCheck,ChevronRight,Clapperboard,Cloud,FolderOpen,ImagePlus,Images,Layers3,LayoutGrid,LoaderCircle,Maximize2,Plus,Search,Settings2,Sparkles,Upload,X } from 'lucide-react';
import { Alert,BusyScope,Button,Checkbox,Choice,Field,Input,Panel,Select } from './components/ui';
import { initialSettings,sampleProducts,categoryLabels,languageLabels,outputLabels } from './lib/types';
import PlanCount from './components/PlanCount';
import CopySourceNotice,{untranslatedLanguage} from './components/CopySourceNotice';
import {freePlanningExplanation} from '../shared/merchant-facts';
import {moduleTypes,moduleNames,moduleRoles,resizeVisualPlan,reviewVisualPlan,plannerSystemPrompt,planVisualStory} from '../shared/visual-planning';
import type {ModuleType} from '../shared/visual-planning';
import {benchmarkProducts} from '../shared/benchmark-products';
import type {BenchmarkProduct} from '../shared/benchmark-products';
import {identifyBenchmark} from './lib/benchmark-assets';
import type { Artifact,Category,CopySection,Language,Product,SavedProject,Settings } from './lib/types';
import { health,planCopy,request,setAccessCode } from './lib/api';
import { track } from './lib/analytics';
import StoryboardPreview,{photoLabel} from './components/StoryboardPreview';
import {buildStoryboard,normaliseSections,roleNames,roleDescriptions,plannedPhotoCalls} from './lib/storyboard';
import { readDraft,readProjects,saveDraft,saveProject } from './lib/storage';
import { readProductFile } from './lib/images';
import { artifactFilename,artifactManifest,downloadBlob,downloadBundle,generateArtifacts } from './lib/render';

const steps=[{title:'商品與渠道',subtitle:'從你的商品開始'},{title:'規劃文案',subtitle:'先確認要說什麼'},{title:'視覺設定',subtitle:'讓整套風格一致'},{title:'成果與下載',subtitle:'檢查後，帶走素材'}];
const tones=[{id:'natural',name:'自然留白',desc:'柔和綠調 · 日常質感',colors:['#e9edde','#a9b99b','#374e3e']},{id:'studio',name:'清透棚拍',desc:'冷白灰藍 · 細節清楚',colors:['#edf1f4','#b4cad5','#304e62']},{id:'bold',name:'暖調撞色',desc:'奶杏暖橘 · 視覺聚焦',colors:['#ffead1','#eab279','#754a36']}] as const;
const layouts=[{id:'smart',name:'智慧匹配',desc:'按用途與商品配色安排'},{id:'center',name:'主體置中',desc:'保留每種用途的分工'},{id:'split',name:'圖文分欄',desc:'商品與說明各自清楚'},{id:'editorial',name:'雜誌構圖',desc:'大圖搭配簡短標題'}] as const;
const emptyCopy:CopySection={id:'preview',title:'讓商品，說出自己的故事。',body:'你的賣點、你的風格。從一張照片，展開一整套素材。',selected:true};
function messageOf(error:unknown){return error instanceof Error?error.message:'處理失敗。請保留目前內容，稍後重試。';}

export default function App(){
 const [page,setPage]=useState<'studio'|'library'>('studio');const [step,setStep]=useState(0);const [product,setProduct]=useState<Product|null>(null);const [settings,setSettings]=useState<Settings>(initialSettings);const [sections,setSections]=useState<CopySection[]>([]);const [artifacts,setArtifacts]=useState<Artifact[]>([]);
 const [busy,setBusy]=useState(false);const [progress,setProgress]=useState('');const [error,setError]=useState('');const [notice,setNotice]=useState('');const [ready,setReady]=useState(false);const [projects,setProjects]=useState<SavedProject[]>([]);const [query,setQuery]=useState('');const [categoryFilter,setCategoryFilter]=useState('all');const [librarySelection,setLibrarySelection]=useState<string[]>([]);
 const [apiStatus,setApiStatus]=useState<'checking'|'online'|'offline'>('checking');const [apiDetails,setApiDetails]=useState<Record<string,unknown>>({});const [copyProvider,setCopyProvider]=useState('');const [advanced,setAdvanced]=useState(false);const [preview,setPreview]=useState<Artifact|null>(null);const [downloadBusy,setDownloadBusy]=useState(false);const [accessValue,setAccessValue]=useState('');const [paidConsent,setPaidConsent]=useState(false);
 const settingsDialog=useRef<HTMLDialogElement>(null);const previewDialog=useRef<HTMLDialogElement>(null);const sourceInput=useRef<HTMLInputElement>(null);const controller=useRef<AbortController|null>(null);const draftWarning=useRef(false);const restored=useRef(false);
 useEffect(()=>{if(restored.current)return;restored.current=true;void track('mono_studio_opened');Promise.all([readDraft(),readProjects()]).then(([draft,items])=>{if(draft?.product){setProduct(draft.product);setSettings({...initialSettings,...draft.settings,detailCount:draft.settings.detailCount??(draft.sections.length||8)});setSections(draft.sections);setStep(Math.min(draft.step,2));setNotice('已恢復上次在此瀏覽器儲存的草稿。');}setProjects(items);}).catch(()=>setError('瀏覽器儲存空間無法讀取。仍可製作與下載，草稿可能無法保存。')).finally(()=>setReady(true));void checkHealth();},[]);
 useEffect(()=>{if(!ready||busy)return;const timer=setTimeout(()=>{saveDraft({product,settings,sections,step}).catch(()=>{if(!draftWarning.current){draftWarning.current=true;setError('草稿未儲存：瀏覽器空間不足或已停用儲存。請先下載素材。');}});},400);return ()=>clearTimeout(timer);},[product,settings,sections,step,ready,busy]);
 useEffect(()=>{if(preview)previewDialog.current?.showModal();},[preview]);
 useEffect(()=>()=>{controller.current?.abort();},[]);
 async function checkHealth(){setApiStatus('checking');try{const data=await health();setApiDetails(data);setApiStatus('online');}catch{setApiDetails({});setApiStatus('offline');}}
 function invalidate(copy=false){setPaidConsent(false);setArtifacts([]);setError('');setNotice('');if(copy){setSections([]);setCopyProvider('');}}
 function changeSetting<K extends keyof Settings>(key:K,value:Settings[K]){if(busy)return;setSettings(prev=>({...prev,[key]:value}));invalidate(['language','platform','prompt'].includes(key));}
 function changeProduct(key:'name'|'facts'|'category',value:string){if(busy)return;setProduct(prev=>prev?{...prev,[key]:value}:prev);invalidate(true);}
 async function applyProductFile(file:File,sample?:typeof sampleProducts[number],benchmarkId?:string){
  const image=await readProductFile(file);
  if(!sample){const known=await identifyBenchmark(file);if(known){sample={id:known.category,name:known.name,facts:known.facts['zh-TW'].join('\n'),file:known.file,caption:known.inputNote};benchmarkId=known.id;}}
  setProduct({id:crypto.randomUUID(),name:sample?.name||file.name.replace(/\.[^.]+$/,''),category:sample?.id||'food',facts:sample?.facts||'',sourceDataUrl:image.dataUrl,sourceName:file.name,sourceWidth:image.width,sourceHeight:image.height,sourceOrigin:benchmarkId?'benchmark':sample?'ai-sample':'uploaded',...(benchmarkId?{benchmarkId}:{})});void track('mono_source_loaded',{category:sample?.id||'food',sourceOrigin:benchmarkId?'benchmark':sample?'ai-sample':'uploaded'});setSections([]);setArtifacts([]);setStep(0);setNotice(benchmarkId?'已載入對標商品原圖。情境樣張為本輪對話內建生圖工具的產出，免費模式不呼叫 Google。':sample?'已載入 AI 生成的示範商品照片。你可以修改商品資料。':'商品照片已載入。請補上你確認過的商品資訊。');
 }
 async function selectFile(file?:File){
  if(!file||busy)return;setError('');setBusy(true);
  try{await applyProductFile(file);}catch(e){setError(messageOf(e));}finally{setBusy(false);if(sourceInput.current)sourceInput.current.value='';}
 }
 async function selectSample(sample:typeof sampleProducts[number]){if(busy)return;setError('');setBusy(true);try{const response=await fetch(sample.file);if(!response.ok)throw new Error('示範商品暫時無法讀取，請重新載入。');await applyProductFile(new File([await response.blob()],sample.id+'.png',{type:'image/png'}),sample);}catch(e){setError(messageOf(e));}finally{setBusy(false);}}
 async function selectBenchmark(item:BenchmarkProduct){if(busy)return;setError('');setBusy(true);try{const response=await fetch(item.file);if(!response.ok)throw new Error('對標商品原圖未能載入。');const blob=await response.blob();await applyProductFile(new File([blob],item.id+'.'+(blob.type.includes('png')?'png':'jpg'),{type:blob.type}),{id:item.category,name:item.name,facts:item.facts['zh-TW'].join('\n'),file:item.file,caption:item.inputNote},item.id);}catch(e){setError(messageOf(e));}finally{setBusy(false);}}
 function goToCopy(){if(!product){setError('請先上傳一張商品照片，或選擇下方範例。');return;}if(!product.name.trim()){setError('請填寫商品名稱。');return;}setError('');setStep(1);window.scrollTo({top:0,behavior:'instant'});}
 async function generateCopy(free=false){if(!product)return;const activeSettings=free?{...settings,mode:'demo' as const}:settings;if(activeSettings.mode==='live'&&!paidConsent){setError('請先確認本次付費規劃，或改用免費規劃。');return;}if(free)setSettings(activeSettings);setBusy(true);setError('');setProgress('正在整理文案建議…');const aborter=new AbortController();controller.current=aborter;
  try{const result=await planCopy(product,activeSettings,aborter.signal,paidConsent);if(!Array.isArray(result.sections)||!result.sections.length)throw new Error('文案回應沒有可編輯內容。請重試。');setSections(normaliseSections(result.sections.map((s,i)=>({...s,id:s.id||String(i),title:s.title,body:s.body,selected:s.selected!==false}))));setCopyProvider(`${result.provider} · ${result.model}`);void track('mono_copy_completed',{category:product.category,language:activeSettings.language,platform:activeSettings.platform,mode:activeSettings.mode,provider:result.provider,model:result.model});setNotice(activeSettings.mode==='demo'?'已依商品資料整理草稿。請確認引用資料與待補項目；這次沒有呼叫 AI。':'AI 套圖規劃已完成。請確認文案與畫面方向。');}catch(e){setError(messageOf(e));}finally{setBusy(false);setProgress('');setPaidConsent(false);}
 }
 function updateSection(index:number,key:'title'|'body'|'selected'|'role'|'visualGoal'|'detailFocus',value:string|boolean){if(busy)return;setSections(old=>old.map((s,i)=>i===index?{...s,[key]:value,...(key==='body'&&typeof value==='string'?{evidencePoints:value.split(/[\n；;。]+/).map(s=>s.trim()).filter(Boolean).slice(0,6),customDiagramText:true}:{}),...(key==='role'?{visualGoal:roleDescriptions[value as keyof typeof roleDescriptions]}:{})}:s));invalidate();}
 function goToVisual(){if(untranslatedLanguage(sections,settings.language)){setError('尚未完成翻譯。請先改用原文，或貼上目標語言商品資料。');return;}if(!sections.some(s=>s.selected)){setError('請至少勾選一段文案。');return;}if(sections.some(s=>s.selected&&(!s.title.trim()||!s.body.trim()))){setError('已勾選的段落需要標題與文案。');return;}setError('');setStep(2);window.scrollTo({top:0,behavior:'instant'});}
 async function generate(free=false){if(!product)return;if(untranslatedLanguage(sections,settings.language)){setError('尚未完成翻譯。請先返回文案並改用原文。');return;}const activeSettings=free?{...settings,mode:'demo' as const}:settings;const calls=plannedPhotoCalls(buildStoryboard(product,activeSettings,sections),activeSettings);if(activeSettings.mode==='live'&&(calls>0||activeSettings.outputs.includes('video'))&&!paidConsent){setError('請先確認本次付費生成，或改用免費預覽。');return;}if(free)setSettings(activeSettings);if(!activeSettings.outputs.length){setError('請至少選擇一種輸出。');return;}if(!sections.some(s=>s.selected)){setError('請至少勾選一段文案。');return;}setError('');setNotice('');setArtifacts([]);setBusy(true);setStep(3);const aborter=new AbortController();controller.current=aborter;const complete:Artifact[]=[];const generationStarted=performance.now();void track('mono_generation_started',{category:product.category,language:activeSettings.language,platform:activeSettings.platform,mode:activeSettings.mode,resolution:activeSettings.resolution,outputKinds:activeSettings.outputs.join(',')});
  try{await generateArtifacts(product,activeSettings,sections,(text,artifact)=>{setProgress(text);if(artifact){complete.push(artifact);setArtifacts([...complete]);}},aborter.signal,{allowPaid:paidConsent});setNotice('素材已完成。請檢查每張用途、原圖細節與文案，再下載使用。');void track('mono_generation_completed',{category:product.category,language:activeSettings.language,platform:activeSettings.platform,mode:activeSettings.mode,resolution:activeSettings.resolution,outputCount:complete.length,durationMs:Math.round(performance.now()-generationStarted)});
  }catch(e){void track('mono_generation_failed',{category:product.category,language:activeSettings.language,mode:activeSettings.mode,outputCount:complete.length,durationMs:Math.round(performance.now()-generationStarted)});setError(e instanceof DOMException&&e.name==='AbortError'?'已停止。完成的素材仍可下載。':messageOf(e));}finally{setBusy(false);setProgress('');setPaidConsent(false);}
 }
 async function save(){if(!product)return;setError('');try{await saveProject({id:product.id,product,settings,sections,artifacts,savedAt:new Date().toISOString()});setProjects(await readProjects());setNotice('已儲存到此瀏覽器的商品列表。');void track('mono_product_saved',{category:product.category,language:settings.language,mode:settings.mode,outputCount:artifacts.length});}catch(e){setError('商品未儲存。'+messageOf(e));}}
 async function sync(){if(!product)return;setBusy(true);setError('');try{await request('/products',{id:product.id,name:product.name,category:product.category,description:product.facts,facts:product.facts.trim()?[product.facts]:[],sourceDataUrl:product.sourceDataUrl,metadata:{settings,sections,artifacts:artifacts.map(artifactManifest),sourceName:product.sourceName,sourceWidth:product.sourceWidth,sourceHeight:product.sourceHeight,sourceOrigin:product.sourceOrigin}});setNotice('商品資料與來源照片已同步到 Supabase。產出檔請另行下載保存。');}catch(e){setError(messageOf(e));}finally{setBusy(false);}}
 async function download(){if(!product)return;setDownloadBusy(true);setError('');try{await downloadBundle(product,settings,sections,artifacts);setNotice('ZIP 已下載，包含原圖、素材、完整文案與生成紀錄。');void track('mono_bundle_downloaded',{category:product.category,language:settings.language,mode:settings.mode,outputCount:artifacts.length});}catch(e){setError(messageOf(e));}finally{setDownloadBusy(false);}}
 async function bulkDownload(){setDownloadBusy(true);setError('');try{for(const p of projects.filter(p=>librarySelection.includes(p.id)))await downloadBundle(p.product,p.settings,p.sections,p.artifacts);setNotice('已下載選取商品的素材包。');}catch(e){setError(messageOf(e));}finally{setDownloadBusy(false);}}
 function openProject(project:SavedProject){if(busy)return;setProduct(project.product);setSettings({...initialSettings,...project.settings,detailCount:project.settings.detailCount??(project.sections.length||8)});setSections(project.sections);setArtifacts(project.artifacts);setStep(project.artifacts.length?3:1);setPage('studio');setError('');setNotice('已開啟此瀏覽器儲存的商品。');}
 function newProject(){if(busy)return;setProduct(null);setSettings(initialSettings);setSections([]);setArtifacts([]);setStep(0);setPage('studio');setError('');setNotice('已建立新的商品草稿。');}
 async function fillMissingRoles(){if(!product||busy)return;try{const free=await planCopy(product,{...settings,mode:'demo'});setSections(resizeVisualPlan(sections,free.sections,settings.detailCount??5));invalidate();setNotice('已套用張數並補齊不同圖種。原有文案保留，沒有呼叫模型。');}catch(e){setError(messageOf(e));}}
 function changeModule(index:number,moduleType:ModuleType){if(!product||busy)return;const suggestions=planVisualStory({name:product.name,category:product.category,description:product.facts,facts:[product.facts]},settings.language,16);const suggestion=suggestions.find(s=>s.moduleType===moduleType);setSections(old=>old.map((s,i)=>i===index?{...s,moduleType,role:moduleRoles[moduleType],visualGoal:suggestion?.visualGoal||s.visualGoal,sceneVariant:suggestion?.sceneVariant||0}:s));invalidate();}
 const chosen=sections.filter(s=>s.selected);const currentCopy=chosen[0]||emptyCopy;const filtered=projects.filter(p=>(categoryFilter==='all'||p.product.category===categoryFilter)&&p.product.name.toLocaleLowerCase().includes(query.toLocaleLowerCase()));
 const shotPlans=product?buildStoryboard(product,settings,sections):[];const newPhotoCount=plannedPhotoCalls(shotPlans,{...settings,mode:'live'});
 const detailCount=settings.detailCount??5;const validCount=Number.isInteger(detailCount)&&detailCount>=1&&detailCount<=16;const planReview=reviewVisualPlan(sections);
 const outputCount=settings.outputs.reduce((count,kind)=>count+(kind==='detail'?chosen.length:1),0);
 const googleService=apiDetails.googleProvider==='gemini-api'?'Google Gemini API':apiDetails.googleProvider==='vertex'?'Google Vertex AI':'尚未確認';
 const readiness=(apiDetails.providers&&typeof apiDetails.providers==='object'?apiDetails.providers:{}) as Record<string,string>;
 const statusLabel=(value?:string)=>value?.endsWith('-ready')?'已設定':value==='demo'?'示範文案':'未設定';
 return <div className="app-shell">
  <aside className="sidebar"><a className="brand" href="#" aria-disabled={busy} onClick={e=>{e.preventDefault();if(!busy)setPage('studio');}} aria-label="Mono Studio 首頁"><span className="brand-mark"><Layers3 size={25}/></span><span>mono<span className="brand-dot">.</span><small>COMMERCE STUDIO</small></span></a>
   <span className="nav-caption">你的工作室</span><nav aria-label="主選單"><button className={page==='studio'?'nav-item active':'nav-item'} disabled={busy} onClick={()=>{if(!busy)setPage('studio');}}><Sparkles size={18}/>素材工作室</button><button className={page==='library'?'nav-item active':'nav-item'} disabled={busy} onClick={()=>{if(busy)return;setPage('library');void readProjects().then(setProjects);}}><FolderOpen size={18}/>商品列表<span className="nav-count">{projects.length}</span></button><a className="nav-item" href="/report/merchant-copy/index.html" target="_blank" rel="noreferrer"><CheckCheck size={18}/>測試與產出報告</a></nav>
   <div className="sidebar-bottom"><div className="small-note"><span className="small-star">✦</span><p>一張商品照片，<br/>展開一整套可能。</p><span>先規劃，再生成。</span></div><button className="nav-item" onClick={()=>settingsDialog.current?.showModal()}><Settings2 size={18}/>模型與連線</button><div className="workspace-person"><span>Z</span><div>我的工作空間<small>採用 CYBERBIZ Pitaya UI</small></div></div></div>
  </aside>
  <div className="workspace"><header className="topbar"><div className="breadcrumb">工作空間 <ChevronRight size={13}/><strong>{page==='studio'?'素材工作室':'商品列表'}</strong></div><div className="topbar-right"><span className={`mode-pill ${settings.mode==='live'?'live':''}`}><i/>{settings.mode==='demo'?'免費預覽':'真實模型'}</span><Button variant="ghost" onClick={newProject} disabled={busy}><Plus size={16}/><span>新建商品</span></Button></div></header>
  <main>
  {page==='studio'?<>
   <div className="page-heading"><div><div className="eyebrow">ONE PRODUCT. A WHOLE COLLECTION.</div><h1>{step===0?'好素材，從一張商品圖開始。':step===1?'先把商品故事，說清楚。':step===2?'選一個風格，串起整套素材。':'你的商品素材，在這裡。'}</h1><p>{step===0?'放上照片，選好渠道。我們一起完成接下來的文案與視覺。':step===1?'每一段都能修改。只生成你勾選的內容。':step===2?'把調性、版型與尺寸一次定好，讓商品保持一致。':'逐張檢查商品與文字，再把整套素材帶走。'}</p></div><span className="draft-indicator">{ready?'草稿保存在此瀏覽器':'載入草稿中'}</span></div>
   <ol className="stepper" aria-label="製作步驟">{steps.map((s,i)=><li key={s.title} className={step===i?'current':step>i?'complete':''}><button onClick={()=>{if(i<step&&!busy){setStep(i);setError('');}}} disabled={i>step||busy} aria-current={step===i?'step':undefined}><span className="step-number">{step>i?<Check size={15}/>:i+1}</span><span><strong>{s.title}</strong><small>{s.subtitle}</small></span></button></li>)}</ol>
   {error&&<Alert>{error}{apiStatus==='offline'&&<button className="inline-link" onClick={()=>void checkHealth()}>重新檢查後端連線</button>}</Alert>}
   <div className="notice" role="status" aria-live="polite">{notice}</div>
   <div className={step===3?'results-layout':'editor-layout'}>
    <Panel className="editor-panel"><BusyScope disabled={busy&&step<3}>
    {step===0&&<>
     <div className="panel-heading"><div><h2>商品照片</h2><p>清楚的主體，能讓後續素材更一致。</p></div><span className="subtle-tag">01 / 商品</span></div>
     <input ref={sourceInput} aria-label="上傳商品照片" type="file" accept="image/png,image/jpeg,image/webp" className="file-input" onChange={e=>void selectFile(e.target.files?.[0])}/>
     <div className={`upload-zone ${product?'has-product':''}`} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!busy)void selectFile(e.dataTransfer.files[0]);}}>
      {product?<><img src={product.sourceDataUrl} alt={product.name+' 原始商品照片'}/><div className="uploaded-info"><span className="success-dot"/>已載入商品照片<strong>{product.sourceName}</strong><small>{product.sourceWidth} × {product.sourceHeight} px · {product.sourceOrigin==='ai-sample'?'AI 生成範例':'你的原始照片'}</small><Button variant="secondary" disabled={busy} onClick={()=>sourceInput.current?.click()}><Upload size={15}/>更換照片</Button></div></>:<><div className="upload-icon"><ImagePlus size={29}/></div><h3>把商品照片拖到這裡</h3><p>或從電腦選擇一張照片</p><Button onClick={()=>sourceInput.current?.click()} disabled={busy}><Plus size={16}/>選擇商品照片</Button><small>PNG、JPG、WebP · 最大 7 MB</small></>}
     </div>
     <div className="samples-label"><span>手邊沒有圖片？試試範例</span><small>AI 生成的虛構商品</small></div>
     <div className="sample-grid">{sampleProducts.map(sample=><button className={`sample-card ${product?.name===sample.name?'selected':''}`} key={sample.id} onClick={()=>void selectSample(sample)} disabled={busy} aria-label={'使用 '+sample.name+' 範例'}><img src={sample.file} alt={sample.name} loading="eager"/><span>{sample.caption}<strong>{sample.name}<ArrowRight size={14}/></strong></span></button>)}</div>
     <details className="benchmark-picker"><summary>用指定品牌白底圖對標</summary><p>原圖與來源保留，情境樣張分開標示。</p><div className="benchmark-grid">{benchmarkProducts.map(item=><button key={item.id} className="benchmark-card" disabled={busy} onClick={()=>void selectBenchmark(item)} aria-label={'使用對標商品 '+item.name}><img src={item.file} alt={item.name}/><strong>{item.name}</strong><small>{categoryLabels[item.category]}</small></button>)}</div></details>{product&&<div className="product-fields"><div className="field-row"><Field label="商品名稱"><Input value={product.name} maxLength={100} onChange={e=>changeProduct('name',e.target.value)}/></Field><Field label="商品類型"><Select value={product.category} onChange={e=>changeProduct('category',e.target.value)}>{Object.entries(categoryLabels).map(([id,name])=><option value={id} key={id}>{name}</option>)}</Select></Field></div><Field label="已確認的商品資訊" hint="填寫實際材質、成分、規格或特色。未知資訊請留白。"><textarea rows={3} value={product.facts} onChange={e=>changeProduct('facts',e.target.value)} maxLength={3000} placeholder="例如：商品材質、包裝容量、使用情境…"/></Field></div>}
     <div className="section-divider"/><div className="panel-heading compact"><div><h2>要在哪裡，和誰說話？</h2><p>平台與輸出語言可以分開選擇。</p></div></div>
     <div className="field-row"><Field label="分發平台" hint="提供構圖起點；上架前仍需確認平台規則。"><Select value={settings.platform} onChange={e=>changeSetting('platform',e.target.value)}>{['Shopee','Amazon','Momo','PChome','品牌官網','社群廣告'].map(x=><option key={x}>{x}</option>)}</Select></Field><Field label="輸出語言"><Select value={settings.language} onChange={e=>changeSetting('language',e.target.value as Language)}>{Object.entries(languageLabels).map(([id,label])=><option value={id} key={id}>{label}</option>)}</Select></Field></div>
     <div className="panel-footer"><span><Check size={14}/>你的原圖會保留</span><Button onClick={goToCopy} disabled={busy}>下一步：規劃文案<ArrowRight size={16}/></Button></div>
    </>}
    {step===1&&<>
     <div className="panel-heading"><div><h2>這次想強調什麼？</h2><p>用平常說話的方式描述就好，也可以直接使用建議。</p></div><span className="subtle-tag">02 / 文案</span></div>
     <Field label="這次的製作方向（Prompt）"><textarea value={settings.prompt} maxLength={2000} onChange={e=>changeSetting('prompt',e.target.value)} rows={3} placeholder="例如：做一套有自然生活感的商品詳情圖，讓第一次看到商品的人看懂特色。"/></Field>
     <div className="prompt-chips">{['讓新客快速看懂商品','強調商品細節與質感','適合日常生活的風格'].map(text=><button key={text} onClick={()=>changeSetting('prompt',text)}>{text}<Plus size={12}/></button>)}</div>
     {settings.mode==='demo'&&product&&<CopySourceNotice product={product} sections={sections} language={settings.language} prompt={settings.prompt} onUseLanguage={language=>{setSettings(old=>({...old,language}));setSections(old=>old.map(section=>({...section,requestedLanguage:language,translationStatus:section.contentLanguage===language?'not-needed':section.translationStatus})));invalidate();setNotice('已改用原文，保留目前編輯內容。');}}/>}
     <PlanCount count={detailCount} onChange={n=>changeSetting('detailCount',n)} onApply={()=>void fillMissingRoles()} hasPlan={sections.length>0} selected={chosen.length}/><div className="copy-action"><small>{settings.mode==='demo'?`依已填資料整理 ${detailCount} 張詳情圖，不使用 AI 改寫或翻譯。`:'AI 文案會呼叫 Gemini 3.7 Flash，可能產生費用。'}</small><div className="copy-action-buttons">{settings.mode==='live'&&<Button variant="secondary" onClick={()=>void generateCopy(true)} disabled={busy}>改用免費規劃</Button>}<Button onClick={()=>void generateCopy()} disabled={busy||!product||!validCount||settings.mode==='live'&&!paidConsent}>{busy?<LoaderCircle className="spin" size={16}/>:<Sparkles size={16}/>} {settings.mode==='demo'?'依商品資料整理（免費）':'AI 規劃文案（付費）'}</Button></div></div>{settings.mode==='live'&&<Checkbox className="paid-consent" aria-label="同意本次付費文案" checked={paidConsent} onChange={e=>setPaidConsent(e.target.checked)} label="我同意這次呼叫付費模型；尚未勾選時不會送出。"/>}
     {sections.length>0?<><div className="section-divider"/><div className="panel-heading compact"><div><h2>每一張，要說什麼？</h2><p>已選 {chosen.length} / {sections.length} 段。文案會直接用在詳情圖。</p></div><button className="inline-link" onClick={()=>{setSections(old=>old.map(x=>({...x,selected:chosen.length!==sections.length})));invalidate();}}>{chosen.length===sections.length?'取消全選':'選取全部'}</button></div>
      <div className="storyboard-upgrade"><span>{planReview.moduleCount} 種圖種 · {planReview.sceneCount} 張使用情境</span><small>照片、特寫與資訊圖各有分工</small></div>{planReview.issues.length>0&&<div className="plan-review-note">{planReview.issues.map(issue=><p key={issue}>{issue}</p>)}</div>}<div className="copy-sections">{sections.map((section,i)=><article className={`copy-card ${section.selected?'selected':''}`} key={section.id}><div className="copy-card-top"><Checkbox checked={section.selected} aria-label={`選取文案 ${i+1}`} label={`畫面 ${String(i+1).padStart(2,'0')}`} onChange={e=>updateSection(i,'selected',e.target.checked)}/><small>{section.selected?'會產生詳情圖':'不產生'}</small></div><div className="shot-purpose-fields"><Field label={`用途 ${i+1}`}><Select value={section.moduleType||normaliseSections(sections)[i].role} onChange={e=>changeModule(i,e.target.value as ModuleType)}>{moduleTypes.map(module=><option value={module} key={module}>{moduleNames[module]}</option>)}</Select></Field>{normaliseSections(sections)[i].role==='detail'&&<Field label={`細節位置 ${i+1}`}><Select value={section.detailFocus||'center'} onChange={e=>updateSection(i,'detailFocus',e.target.value)}><option value="upper">原圖上方</option><option value="center">原圖中央</option><option value="lower">原圖下方</option></Select></Field>}</div><Input className="copy-title" aria-label={`標題 ${i+1}`} maxLength={160} value={section.title} onChange={e=>updateSection(i,'title',e.target.value)}/><textarea aria-label={`文案 ${i+1}`} value={section.body} maxLength={1200} rows={3} onChange={e=>updateSection(i,'body',e.target.value)}/><Field label={`畫面方向 ${i+1}`}><textarea rows={3} value={section.visualGoal||roleDescriptions[normaliseSections(sections)[i].role!]} maxLength={1000} onChange={e=>updateSection(i,'visualGoal',e.target.value)}/></Field><div className="copy-count">{section.body.length} / 1200</div>{section.copyOrigin&&<details className="copy-evidence"><summary>這段引用了哪些資料？</summary><p>以下是原始輸入。手動修改文案後，請再次核對。</p>{section.sourceFacts?.length?<ul>{section.sourceFacts.map((fact,j)=><li key={j}>{fact}</li>)}</ul>:<p>沒有對應資料。請補充或取消勾選這張。</p>}{Boolean(section.missingFields?.length)&&<p>待補資料：{section.body}</p>}</details>}</article>)}</div><p className="review-note">請確認商品事實與宣稱。未提供的成分、認證與效果，不應當作已確認資訊。</p>
      <button className="inline-link muted-link" onClick={()=>setAdvanced(!advanced)}>{advanced?'收起整理依據':settings.mode==='demo'?'查看這次的整理依據':'查看規劃 Agent 的 Prompt'}</button>{advanced&&<pre className="metadata">{copyProvider||'已儲存的文案'}{'\n'}{settings.platform} · {languageLabels[settings.language]}{'\n\n'}{settings.mode==='demo'&&product?freePlanningExplanation({name:product.name,category:product.category,description:product.facts,facts:[product.facts]},settings.language,validCount?detailCount:8,settings.prompt):plannerSystemPrompt(validCount?detailCount:8,product?.category||'food',product?.name||'')}</pre>}
     </>:<div className="empty-copy"><Layers3 size={32}/><p>先產生建議，再決定要留下哪些內容。</p></div>}
     <div className="panel-footer"><Button variant="ghost" onClick={()=>setStep(0)} disabled={busy}><ArrowLeft size={16}/>返回商品設定</Button><Button onClick={goToVisual} disabled={busy||!validCount||Boolean(untranslatedLanguage(sections,settings.language))}>下一步：視覺設定<ArrowRight size={16}/></Button></div>
    </>}
    {step===2&&<>
     <div className="panel-heading"><div><h2>同一個商品，同一套調性。</h2><p>風格會套用到整組素材，原始商品照片保持可追溯。</p></div><span className="subtle-tag">03 / 視覺</span></div>
     <h3 className="group-title">整體調性</h3><div className="tone-grid">{tones.map(t=><Choice key={t.id} selected={settings.tone===t.id} onClick={()=>changeSetting('tone',t.id)} label={t.name}><span className="swatch-row">{t.colors.map(c=><i key={c} style={{background:c}}/>)}</span><strong>{t.name}</strong><small>{t.desc}</small></Choice>)}</div>
     <h3 className="group-title">版型安排</h3><div className="layout-grid">{layouts.map(l=><Choice key={l.id} selected={settings.layout===l.id} onClick={()=>changeSetting('layout',l.id)} label={l.name}><span className={`layout-icon ${l.id}`}><i/><b/><em/></span><strong>{l.name}</strong><small>{l.desc}</small></Choice>)}</div>
     <h3 className="group-title">這次需要哪些素材？</h3><div className="output-options">{(['main','detail','banner','video'] as const).map(kind=><Checkbox className={settings.outputs.includes(kind)?'output-option selected':'output-option'} key={kind} aria-label={outputLabels[kind]} checked={settings.outputs.includes(kind)} onChange={e=>changeSetting('outputs',e.target.checked?[...settings.outputs,kind]:settings.outputs.filter(x=>x!==kind))} label={<>{kind==='video'?<Clapperboard size={20}/>:kind==='detail'?<Layers3 size={20}/>:<Images size={20}/>}<span><strong>{outputLabels[kind]}</strong><small>{kind==='main'?'1 張 · 保留原圖':kind==='detail'?`${chosen.length} 張 · 依用途分工` :kind==='banner'?'1 張 · 橫幅構圖':'1 支 · 8 秒短片'}</small></span></>}/>)}</div>
     {settings.outputs.includes('banner')&&<div className="banner-settings"><Field label="Banner 比例"><Select value={settings.bannerRatio} onChange={e=>changeSetting('bannerRatio',e.target.value as Settings['bannerRatio'])}><option value="16:9">16:9 · 活動橫幅</option><option value="21:9">21:9 · 寬版官網橫幅</option></Select></Field><p>文案與商品分開放置，四周保留安全邊界。選「雜誌構圖」可把商品放到左側。</p></div>}
     <div className="section-divider"/><div className="resolution-row"><div><h3>圖片解析度</h3><p>最長邊像素 · 影片固定 720p</p></div><div className="segmented" role="group" aria-label="輸出解析度">{(['1K','2K','4K'] as const).map(r=><button key={r} aria-pressed={settings.resolution===r} className={settings.resolution===r?'active':''} onClick={()=>changeSetting('resolution',r)}>{r}</button>)}</div></div>
     <p className="review-note">{settings.resolution==='1K'?'最長邊 1024 px':settings.resolution==='2K'?'最長邊 2048 px':'最長邊 4096 px'}。示範輸出是原圖組版；提高解析度不會補出原圖不存在的細節。</p>
     {settings.outputs.includes('video')&&<p className="review-note">{settings.mode==='demo'?'示範短片使用原圖做動態排版，無配音。請保持此分頁開啟約 8 秒。':'真實影片使用 Veo 3.1，需另外設定標準 Vertex 專案與存取權杖。'}</p>}
     {product&&<StoryboardPreview product={product} settings={settings} sections={sections}/>}<div className="generation-summary"><span>{settings.platform} · {languageLabels[settings.language]}</span><strong>{outputCount} 份素材</strong><small>{settings.mode==='demo'?'使用免費版型、原圖裁切與既有範例場景，0 次模型呼叫。':`這套需要 ${newPhotoCount} 次新照片請求${settings.outputs.includes('video')?'，另加 1 次影片':''}。主圖、原圖細節與規格不重複生圖。`}</small></div>
     {settings.mode==='live'&&(newPhotoCount>0||settings.outputs.includes('video'))&&<Checkbox className="paid-consent" aria-label="同意本次付費生成" checked={paidConsent} onChange={e=>setPaidConsent(e.target.checked)} label={`我同意這次 ${newPhotoCount} 次照片請求${settings.outputs.includes('video')?'與 1 次影片請求':''}的費用。`}/>}<div className="panel-footer"><Button variant="ghost" onClick={()=>setStep(1)}><ArrowLeft size={16}/>返回文案</Button>{settings.mode==='live'&&<Button variant="secondary" onClick={()=>void generate(true)} disabled={busy}>免費預覽並下載</Button>}<Button onClick={()=>void generate()} disabled={busy||settings.mode==='live'&&(newPhotoCount>0||settings.outputs.includes('video'))&&!paidConsent}><Sparkles size={16}/>{settings.mode==='demo'?'開始生成':newPhotoCount>0||settings.outputs.includes('video')?'開始 AI 生成（付費）':'直接組版（不呼叫模型）'}</Button></div>
    </>}
    {step===3&&<>
     <div className="panel-heading"><div><h2>{busy?'正在完成你的素材…':artifacts.length===outputCount&&outputCount>0?'素材已完成':artifacts.length?'部分素材已完成':'準備重新製作'}</h2><p>{product?.name} · {languageLabels[settings.language]} · {settings.resolution}</p></div><span className="subtle-tag">{artifacts.length} 份已完成</span></div>
     {busy&&<div className="generation-progress" role="status"><LoaderCircle size={20} className="spin"/><span>{progress}</span><Button variant="secondary" onClick={()=>controller.current?.abort()}>停止等待</Button></div>}
     <div className="result-actions"><Button variant="secondary" onClick={()=>{setStep(2);setError('');}} disabled={busy}><ArrowLeft size={16}/>修改設定</Button><div><Button variant="secondary" onClick={()=>void save()} disabled={busy||!artifacts.length}><FolderOpen size={16}/>儲存到商品列表</Button><Button onClick={()=>void download()} disabled={downloadBusy||!artifacts.length}>{downloadBusy?<LoaderCircle size={16} className="spin"/>:<ArrowDownToLine size={16}/>}下載全部素材</Button></div></div>
     <p className="provenance-note">{settings.mode==='demo'?'本次為免費預覽：每張按用途組版，細節來自原圖裁切；範例商品可使用已備好的場景照片。沒有呼叫 Gemini 或 Veo。':'新場景只用於主視覺與情境，Banner 優先共用場景；主圖、細節與規格保留原圖。實際服務與模型請看每張生成紀錄，並逐張檢查商品一致性。'}ZIP 包含所有素材、原圖、文案與生成紀錄。</p>
     <div className="result-grid">{artifacts.map((artifact,i)=><ArtifactCard key={artifact.id} artifact={artifact} index={i} onPreview={()=>setPreview(artifact)}/>)}</div>
     {artifacts.some(a=>a.warning)&&<Alert>{Array.from(new Set(artifacts.filter(a=>a.warning).map(a=>a.warning))).join(' ')}</Alert>}
     {artifacts.some(a=>a.kind==='detail')&&<details className="detail-preview"><summary>查看連續詳情頁 <span>{artifacts.filter(a=>a.kind==='detail').length} 張</span></summary><div>{artifacts.filter(a=>a.kind==='detail').map(a=><BlobImage key={a.id} artifact={a}/>)}</div></details>}
     <div className="remote-save"><Cloud size={16}/><p>本機商品列表與 Supabase 分開保存。遠端同步會上傳來源照片與商品資料。</p><Button variant="secondary" onClick={()=>void sync()} disabled={busy||apiStatus!=='online'}>同步商品到 Supabase</Button></div>
    </>}
    </BusyScope></Panel>
    {step<3&&<aside className="preview-panel" aria-label="即時版型預覽"><div className="preview-heading"><span>你的素材方向</span><span className="subtle-tag">即時預覽</span></div><div className={`live-preview ${settings.tone} ${settings.layout}`}>
      <div className="preview-topline"><span>MONO / COLLECTION</span><span>✦</span></div>
      <div className="live-preview-copy"><small>{product?.name||'從一張照片開始'}</small><h2>{step===0?'讓好商品，\n被好好看見。':currentCopy.title}</h2><p>{step===0?'你的下一套商品素材，\n從這裡開始。':currentCopy.body}</p></div>
      <div className="preview-photo">{product?<img src={product.sourceDataUrl} alt="商品版型預覽"/>:<img src="/samples/fashion.png" alt="休閒鞋示範構圖"/>}</div><div className="preview-bottomline"><span>{languageLabels[settings.language]}</span><span>{settings.platform}</span></div>
     </div><div className="mini-contact"><div><img src={product?.sourceDataUrl||'/samples/fashion.png'} alt="白底構圖示意"/><span>主圖</span></div><div className={settings.tone}><i/><img src={product?.sourceDataUrl||'/samples/fashion.png'} alt="詳情構圖示意"/><span>詳情</span></div><div className={'mini-banner '+settings.tone}><i/><img src={product?.sourceDataUrl||'/samples/fashion.png'} alt="橫幅構圖示意"/><span>Banner</span></div></div>
     <p className="preview-disclaimer">構圖示意。完成生成後，可查看與下載實際圖片。</p><div className="preview-checks"><h3>一起保持一致</h3><p><Check size={14}/>同一張商品原圖</p><p><Check size={14}/>同一套色調與文案</p><p><Check size={14}/>各渠道獨立輸出尺寸</p></div>
    </aside>}
   </div>
  </>:<>
   <div className="page-heading"><div><div className="eyebrow">YOUR PRODUCT LIBRARY</div><h1>商品列表</h1><p>保留每個商品的照片、文案與完成的素材。</p></div><Button onClick={newProject}><Plus size={16}/>新建商品</Button></div>
   {error&&<Alert>{error}</Alert>}<div className="notice" role="status">{notice}</div>
   <div className="library-toolbar"><label className="search-field"><Search size={18}/><Input aria-label="搜尋商品" placeholder="搜尋商品名稱" value={query} onChange={e=>setQuery(e.target.value)}/></label><Select aria-label="篩選商品類型" value={categoryFilter} onChange={e=>setCategoryFilter(e.target.value)}><option value="all">全部類型</option>{Object.entries(categoryLabels).map(([id,label])=><option value={id} key={id}>{label}</option>)}</Select><span>{filtered.length} 個商品</span><Button variant="secondary" onClick={()=>void bulkDownload()} disabled={!librarySelection.length||downloadBusy}>下載已選 {librarySelection.length} 項</Button></div>
   <p className="review-note">儲存在此瀏覽器。清除瀏覽器資料會移除這些紀錄，請下載備份。</p>
   {filtered.length?<div className="library-grid">{filtered.map(p=><article className="library-card" key={p.id}><div className="library-select"><Checkbox aria-label={'選取商品 '+p.product.name} checked={librarySelection.includes(p.id)} onChange={e=>setLibrarySelection(prev=>e.target.checked?[...prev,p.id]:prev.filter(x=>x!==p.id))}/></div><img src={p.product.sourceDataUrl} alt={p.product.name}/><div><span className="eyebrow">{categoryLabels[p.product.category]} · {languageLabels[p.settings.language]}</span><h2>{p.product.name}</h2><p>{p.artifacts.length} 份素材 · {new Date(p.savedAt).toLocaleDateString('zh-TW')}</p><Button variant="secondary" disabled={busy} onClick={()=>openProject(p)} aria-label={'繼續編輯 '+p.product.name}>繼續編輯<ArrowRight size={15}/></Button></div></article>)}</div>:<div className="library-empty"><FolderOpen size={42}/><h2>{projects.length?'沒有符合條件的商品':'第一個商品，從這裡開始。'}</h2><p>{projects.length?'試試其他關鍵字或類型。':'完成素材後，按「儲存到商品列表」就會出現在這裡。'}</p>{!projects.length&&<Button onClick={newProject}>製作第一套素材<ArrowRight size={16}/></Button>}</div>}
  </>}
  </main><footer className="workspace-footer"><span>mono. studio · 資料整理 v4</span><span>先確認內容，再讓好商品被看見。</span><button onClick={()=>settingsDialog.current?.showModal()}><i className={apiStatus==='online'?'online':'offline'}/>{apiStatus==='online'?'後端已連線':apiStatus==='checking'?'檢查連線中':'後端未連線'}</button></footer></div>
  <dialog ref={settingsDialog} className="settings-dialog" aria-labelledby="model-dialog-title"><div className="dialog-heading"><div><span className="eyebrow">WORKSPACE SETTINGS</span><h2 id="model-dialog-title">模型與連線</h2></div><button className="icon-button" aria-label="關閉模型設定" onClick={()=>settingsDialog.current?.close()}><X size={20}/></button></div><p>示範模式可以測試流程。真實生成需要伺服器端金鑰與工作室連線代碼。</p><Field label="生成模式"><Select value={settings.mode} onChange={e=>{changeSetting('mode',e.target.value as Settings['mode']);setStep(Math.min(step,1));}} disabled={busy}><option value="demo">免費預覽 · 套圖規劃與組版</option><option value="live">Google 模型 · 真實生成</option></Select></Field><div className="provider-readiness" role="status"><strong>目前服務：{apiStatus==='online'?googleService:'後端未連線'}</strong><p>文案：{statusLabel(readiness.copy)} · 圖片：{statusLabel(readiness.image)} · 影片：{statusLabel(readiness.video)}</p><small>「已設定」只表示後端具備設定；真正可用仍需通過模型呼叫。</small></div><div className="model-list"><div><span>文案規劃</span><strong>Gemini 3.7 Flash</strong><code>gemini-3.7-flash</code></div><div><span>圖片生成</span><strong>Nano Banana 2</strong><code>gemini-3.1-flash-image</code></div><div><span>影片生成</span><strong>Veo 3.1</strong><code>veo-3.1-generate-001</code></div></div><Field label="工作室連線代碼" hint="由部署者設定的存取代碼，不是 Google API Key。只保留在本次分頁記憶體。"><Input type="password" disabled={busy} value={accessValue} autoComplete="off" onChange={e=>{setAccessValue(e.target.value);setAccessCode(e.target.value);}} placeholder="真實模型模式需要此代碼"/></Field><details><summary>部署者設定說明</summary><p>Google Gemini API 優先使用 MONO_GEMINI_API_KEY，或使用 GEMINI_API_KEY；Vertex AI 使用 VERTEX_API_KEY 或標準雲端設定，依後端選擇服務。真實生成另需 MONO_LIVE_ACCESS_CODE。Veo 需另設定 GOOGLE_CLOUD_PROJECT 與 VERTEX_ACCESS_TOKEN。Google 金鑰保留在後端的環境設定，雲端使用 Supabase Secrets，完整方式請見 repo README。</p><p>Veo 3.0 已退役，本專案使用官方替代的 Veo 3.1。影片是否可用，仍需依標準 Vertex 專案的權限與配額確認。</p><pre className="metadata">{JSON.stringify(apiDetails,null,2)}</pre></details><div className="dialog-footer"><span className="connection-status">{apiStatus==='online'?'後端已連線':apiStatus==='checking'?'檢查中':'後端未連線'}</span><Button variant="secondary" onClick={()=>void checkHealth()}>檢查連線</Button><Button onClick={()=>settingsDialog.current?.close()}>完成設定</Button></div></dialog>
  <dialog ref={previewDialog} className="image-dialog" aria-labelledby="image-dialog-title" onClose={()=>setPreview(null)}><div className="dialog-heading"><h2 id="image-dialog-title">{preview?.title}</h2><button className="icon-button" aria-label="關閉圖片預覽" onClick={()=>{previewDialog.current?.close();setPreview(null);}}><X size={20}/></button></div>{preview&&<><BlobImage artifact={preview} controls/><p>{preview.width} × {preview.height} px · {preview.provider} · {preview.model}</p><details><summary>文案與生成指令</summary><pre className="metadata">{preview.prompt}</pre></details></>}</dialog>
 </div>;
}

function useBlobUrl(blob:Blob){const [url,setUrl]=useState('');useEffect(()=>{const u=URL.createObjectURL(blob);setUrl(u);return ()=>URL.revokeObjectURL(u);},[blob]);return url;}
function BlobImage({artifact,controls=false}:{artifact:Artifact;controls?:boolean}){const url=useBlobUrl(artifact.blob);if(!url)return <span aria-label="載入素材中"/>;return artifact.kind==='video'?<video src={url} controls={controls} preload="metadata" muted playsInline/>:<img src={url} alt={artifact.title} loading="lazy"/>;}
function ArtifactCard({artifact,index,onPreview}:{artifact:Artifact;index:number;onPreview:()=>void}){return <article className={'artifact-card '+artifact.kind} data-testid="artifact-card"><button className="artifact-preview" onClick={onPreview} aria-label={'預覽 '+artifact.title}><BlobImage artifact={artifact}/><span><Maximize2 size={17}/></span></button><div className="artifact-info"><small>{outputLabels[artifact.kind]} · {artifact.width} × {artifact.height}</small><h3>{artifact.title}</h3>{artifact.visualRole&&<small className="artifact-role">{artifact.visualRole==='banner'?'橫幅構圖':artifact.visualRole==='packshot'?'保留原圖':artifact.visualRole==='video'?'短片':roleNames[artifact.visualRole]}</small>}<div><span>{artifact.photoOrigin?photoLabel(artifact.photoOrigin,artifact.photoProvider):artifact.provider.startsWith('demo')?'免費組版':'AI 生成'} · {(artifact.blob.size/1024/1024).toFixed(2)} MB</span><button className="icon-button" aria-label={'下載 '+artifact.title} onClick={()=>downloadBlob(artifact.blob,artifactFilename(artifact,index))}><ArrowDownToLine size={17}/></button></div></div></article>;}
